name: godot-dqn
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - jupyter
  - ipykernel
  - numpy<2
  - matplotlib
  - websockets
  - pip
